[book]
authors = ["Matthew J. Berger"]
language = "en"
multilingual = false
src = "src"
title = "Let's Build a Renderer"

[rust]
edition = "edition2018"

[output.html]
default-theme = "dark"
preferred-dark-theme = "ayu"
mathjax-support = true
google-analytics = "UA-77444816-1"